dist: xenial
language: python
python:
  - "3.8-dev"
  - "3.7"
  - "3.6"

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codeco

# run tests
script:
  - python -m unittest
  - coverage run -m unittest
  - codecov
